name: release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  TAG: ${{ github.ref_name }}
  REGISTRY: ghcr.io

permissions:
  contents: write # Allow to create a release.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: setupGo
      uses: actions/setup-go@v4
      with:
        go-version: '=1.21.3'
    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build docker image
      run: make docker-build-all TAG=${{ env.TAG }}
    - name: Push docker image
      run: make docker-push-all TAG=${{ env.TAG }}
  release:
    name: Create draft release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run:  echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create draft GH release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.TAG }} --draft --generate-notes
